version: '3'
#https://documentation.portainer.io/v2.0/deploy/ceinstalldocker/
#docker run -d -p --restart=always -v  -v
services:
  portainer:
    image: portainer/agent
    restart: always
    ports:
      - ${PORTAINER_PORT}:9001
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"